classdef Cell < manookinlab.sources.Cell
    
    methods
        
        function obj = Cell()
            import symphonyui.core.*;
            
            obj.addProperty('type', 'unknown', ...
                'type', PropertyType('char', 'row', containers.Map( ...
                    {'unknown', 'RGC', 'amacrine', 'bipolar', 'horizontal', 'photoreceptor'}, ...
                    {{}, ...
                    {'ON-parasol', 'OFF parasol', 'ON midget', 'OFF midget', 'small bistratified','ON smooth monostratified','OFF smooth monostratified','broad thorny','recursive bistratified','large bistratified','ON narrow thorny', 'OFF narrow thorny', 'ON recursive', 'large sparse', 'ON', 'OFF', 'ON-OFF', 'melanopsin'}, ...
                    {'AII', 'A17', 'A1', 'ON-starburst', 'OFF-starburst', 'ON-wiry', 'OFF-wiry', 'ON stellate varicose', 'OFF stellate varicose', 'ON', 'OFF', 'ON-OFF'}, ...
                    {'OFF-diffuse', 'OFF-midget', 'ON-diffuse', 'ON-midget', 'rod'}, ...
                    {}, ...
                    {'S cone', 'M cone', 'L cone', 'rod'}})), ...
                'description', 'The confirmed type of the recorded cell');
            
            % Quality property
            obj.addProperty('quality', '', ...
                'type', PropertyType('char', 'row', {'', 'EXCELLENT', 'HIGH', 'MEDIUM','LOW'}), ... 
                'description', 'Quality');
            
            obj.addAllowableParentType('manookinlab.sources.primate.Preparation');
        end
        
    end
    
end

